### ISSUE TITLE
Socratic Seminar 3

### ISSUE THREAD

**Issue by nully0x** [BitDevsAbuja/bitdevsabuja.org#2]
Collection of  topics for the next meetup
Date: October 26th 2024

Announcements

---

Suggested Topics and Developments
Bitcoin

-

---

Mining

-

---

### Chain Sourcing for LDK Nodes

-     Brief overview of LN and LN Channels
-     Node responsibility: Channel State Management and Chain Observation
-     Responsibility segregation: Channel Management, Chain and Channel Monitoring
-     Info Aside: Observer Pattern
-     Chain Sourcing
-         The Listen Interface
-         The Confirm/Filter Interface Combination
-     Challenges
-     Conclusion

Presenter -  Enigbe Ochekliye

---

Ecash

-

---

Other Bitcoin Tech

-

---

Regulatory

-

---

Extras

-

---

Upcoming Events

**Comment by enigbe** [comment]
Hi @nully0x,

Here is an initial draft of a presentation I would like to make on a lightning-related topic. 
The tentative title & TOC are listed below.

### Inside Lightning: Chain Sourcing for LDK Nodes
1. Brief overview of LN and LN Channels
2. Node responsibility: Channel State Management and Chain Observation
3. Responsibility segregation: Channel Management, Chain and Channel Monitoring
4. Info Aside: Observer Pattern
5. Chain Sourcing
    - The Listen Interface
    - The Confirm/Filter Interface Combination
6. Challenges
7. Conclusion

I have gained a lot of insight from reading rust-lightning and contributing to ldk-node repositories and would be happy to share what I have learned so far. 

Please let me know if you have any questions/suggestions on the outline and I'll be happy to discuss them. I would like some agreement/alignment before I proceed with preparation.

Looking forward to hearing from you.

**Comment by nully0x** [comment]
Hello @enigbe this looks good, I will update the content to agenda to reflect the proposed topics.

Thanks
